### ISSUE TITLE
About vis[Bug/issue]

### ISSUE THREAD

**Issue by zz7379** [lab4d-org/lab4d#24]
Your work help me a lot! But i don't understand what "vis" is used for. The "vis.mp4" for me seems not right.
Also, i notice that there is an obvious view-depend RGB, which may not consistant with groud-truth.
![image](https://github.com/lab4d-org/lab4d/assets/44969890/e8373743-635e-47ad-9f5a-ed998b59855e)
![Screenshot 2023-10-18 210423](https://github.com/lab4d-org/lab4d/assets/44969890/aaa334f2-8cf1-4ca4-83ae-a813ed6d36aa)
![Screenshot 2023-10-18 210339](https://github.com/lab4d-org/lab4d/assets/44969890/4232024e-38c5-42c8-93a8-de9794b46b35)

**Comment by gengshan-y** [comment]
Hi, my hunch is that it is a visualization issue. As long as the other renderings look reasonable, I wound't worry about it too much. To give more information, the "vis" renders the [visibility loss](https://github.com/lab4d-org/lab4d/blob/51f400f598631d9ba5b347dfa46292581494793e/lab4d/utils/render_utils.py#L81-L90). It is supposed to be small value everywhere
https://github.com/lab4d-org/lab4d/assets/13134872/fe0d2693-f4ca-4a64-9396-8709dfd09dd5

The above result is from the PPR branch, which will be merged into main branch. 

The artifact might be caused by a speed-up trick [here](https://github.com/lab4d-org/lab4d/blob/b2273f010f0edf7e479f5a56979b7840a8bb79f5/lab4d/nnutils/nerf.py#L738-L742), where only points close to the gaussian bones are queried. Setting to `valid_idx` to None should reduce artifacts although rendering will be slower at test time.

**Comment by zz7379** [comment]
Thanks for your reply. Follow your suggestion, i set` valid_idx` to None when evaluating. But i still got **view-dependent** texture.

https://github.com/lab4d-org/lab4d/assets/44969890/c5a18224-176c-46d2-bf59-c7ce991ce080

Compared to previous result, it only add some floaters in the space. Could you please provide more advise?

**Comment by gengshan-y** [comment]
Hi, I found this flicking artifact to be caused by insufficient depth samples. If you increase the n_depth to 256 at [here](https://github.com/lab4d-org/lab4d/blob/51f400f598631d9ba5b347dfa46292581494793e/lab4d/nnutils/nerf.py#L696), flickering will go away.

https://github.com/lab4d-org/lab4d/assets/13134872/022da9de-76ac-4252-beb1-036353e42698

**Comment by zz7379** [comment]
Wow! It DO works! Thanks for your patient reply!
