### ISSUE TITLE
[Bug/issue] Why i get grid-like artifacts when train with only a few video clips?

### ISSUE THREAD

**Issue by zz7379** [lab4d-org/lab4d#33]
seq="coco-3"
bash scripts/train.sh lab4d/train.py 6 --seqname $seq --logname base --fg_motion bob --num_rounds 40

https://github.com/lab4d-org/lab4d/assets/44969890/df1c744d-5e07-4059-8d54-e022b292c16b

https://github.com/lab4d-org/lab4d/assets/44969890/dd3c96f2-fb72-4983-a0fd-223c23d40b78

 
 (Addition question: is the **anchor_x = (0, 4000)** right when i set **num_rounds** to 40 or 120?

**Comment by gengshan-y** [comment]
Hi sorry for the late reply, this grid artifact happens when there is not sufficient visual evidence to fit the model which might be too flexible. This is expected and there are a few ways if you want to impmrove it: 

(1) the most straightforward way is to lower the [positional encoding](https://github.com/lab4d-org/lab4d/blob/51f400f598631d9ba5b347dfa46292581494793e/lab4d/nnutils/nerf.py#L67) from 10 to 8 or 6 will make the model less flexible but smoother.
(2) another fix is to use the PPR branch, where we adopted the numerical graidents from [neuralangelo](https://github.com/nvlabs/neuralangelo), which makes eikonal loss more well-behaved and better encourages a valid surface than analytical gradient in the main branch

**Comment by zz7379** [comment]
Problem solved by your instruction! Thanks gengshan!
