### ISSUE TITLE
[issue]  Is there any advise decrease the noise point and stripe in rendered model?

### ISSUE THREAD

**Issue by zz7379** [lab4d-org/lab4d#38]
Hi, Gengshan! My bear has many brown or black dots and stripes on its body, which is abnormal, while normal looks fine. Is there any way to improve this?

https://github.com/lab4d-org/lab4d/assets/44969890/c6c0d4a9-b7db-4078-940d-568e1ce55e4f

https://github.com/lab4d-org/lab4d/assets/44969890/9fff4094-e7e9-4d38-a769-e1af675fe895

**Comment by gengshan-y** [comment]
Hi Xinzhou, my haunch is that the color model is too flexible but there is not enough meaningful data to fit it, along this same line as [this thread](https://github.com/lab4d-org/lab4d/issues/33). 

Since you observed the geometry is fine, I would guess using the same number of frequency for color as the number for geometry would help, .e.g, changing num_freq_xyz+2 to num_freq_xyz [here](https://github.com/lab4d-org/lab4d/blob/545a56ff1eace1ebe19a383c42d13a62ae234811/lab4d/nnutils/nerf.py#L112).

Another potential solution is to render from higher-res grid at train time.

**Comment by zz7379** [comment]
Unluckily, changing num_freq_xyz does not work. I double it is caused by my generative loss. I would like to change my 3D representation and give it another try. If it works I will report the result here.
