### ISSUE TITLE
[Bug/issue]Extracted skeletons stretched out of the mesh

### ISSUE THREAD

**Issue by Batwho** [lab4d-org/lab4d#48]
Hello,

I'm running lab4d on a given penguin video and trained another model from scratch for Fish category with around 50 video clips. However, the extracted skeletons don't fit within the meshes, but stretching out. Screenshot of the meshes and skeletons are shown below. I tried with the cat video and its skeleton looks correct. I wonder what might causing such issue and do you have any suggestions on resolving that?
![fish](https://github.com/user-attachments/assets/acb6ab64-f7d2-41b9-9b30-67401ebfe0cc)
![penguin](https://github.com/user-attachments/assets/bc50abec-1131-4ce1-8bc9-315e3dbc629b)

**Comment by gengshan-y** [comment]
Hi, there are two losses that enforces the skeleton to align with the shape: (1) [gauss_skin_consistency_loss](https://github.com/lab4d-org/lab4d/issues/45#issuecomment-2133725669) and (2) [gauss_mask_loss](https://github.com/lab4d-org/lab4d/blob/6591776d7f983fa47e51dde2ae00f449f837849a/lab4d/engine/model.py#L497-L502). (1) forces the gaussians defined by the skeleton to match the NeRF density, and (2) forces the rendered gaussian silhouette to match the NeRF silhouette.

Therefore you may want to check the rendered gaussian silhouette in the tensorborad images tab, and see if that looks reasonable.

Besides, did you pass a fish skeleton when using `--fg_motion skel-xx`? If the quadruped skeleton is being used, it would be difficult to get the alignment working due to the different morphology. In such cases, `--fg_motion bob` is more suitable since it uses a bag of bones at the same level of hierarchy.

**Comment by Batwho** [comment]
Thank you very much, I will check if I could increase the weight of those loss and retrain the model to get a better result. 
Actually, I also see some cases that the skeleton might not align with the rendered mesh's limb e.g. the squirrel skeleton's left arm doesn't match with the mesh's left arm, this is using the provided preprocessed data and checkpoints. Do you have related loss to control that?
![squi](https://github.com/user-attachments/assets/00a2ac65-f0c8-43a0-92b4-a46ddfc654cd)

For fish case, I do use my own fish skeleton to run the model with 50 videos 70 frames each. Do you think that's enough of the data to make the skeleton align with the shape?

**Comment by gengshan-y** [comment]
Hi, the results you showed look reasonable. These misalignment are expected. 

PPR branch typically has better alignment than the main branch, due to a use of more powerful [gauss_skin_consistency_loss](https://github.com/lab4d-org/lab4d/blob/7ac01d3b9ef73667046445c0823fc0772db50079/lab4d/nnutils/deformable.py#L249), which computes the optimal transport between bone gaussians to the canonical mesh, and forces them to align.

**Comment by Batwho** [comment]
I see, will check the PPR. Thank you very much!
